### ISSUE TITLE
Add support for domains list

### ISSUE THREAD

**Issue by codingo** [Ice3man543/subfinder#28]
In many programs you will want to test more  than one domain. It would be ideal to be able to stdin a list of domains, or provide one on the command line in lue of the -d flag.

**Comment by Ice3man543** [comment]
I will work on this feature. I have been meaning to do it from a long time but haven't been able to due to work. Next 2 days, i will implement this and some other features. :+1:

**Comment by Ice3man543** [comment]
Updated code structure of passive enumeration and outputs almost fully. Now, we can use -dl switch to use a text file as argument and write json or text output either in a single file or multiple files in a directory based on domain names. :+1:
