### ISSUE TITLE
No error handling for the blank argument

### ISSUE THREAD

**Issue by madaratech** [Ice3man543/subfinder#31]
## What's the problem (or question)?
Missing error management. 

## Do you have an idea for a solution?
Display generic error for missing required argument or display help menu for blank input.

## How can we reproduce the issue?

1. `./subfinder` (without any argument)

## What are the running context details?

* Installation method : **go get**
* Client OS (e.g. `Microsoft Windows 10`): **Mac OS**
* Relevant console output (if any):

```
MacBook-Pro:bin tech$ ./subfinder 

   ____     __   _____         __       
  / __/_ __/ /  / __(_)__  ___/ /__ ____
 _\ \/ // / _ \/ _// / _ \/ _  / -_) __/
/___/\_,_/_.__/_/ /_/_//_/\_,_/\__/_/   
                                      

SubFinder v0.1.0 	  Made with ❤ by @Ice3man
==================================================


[-] Searching For Subdomains in Censys
[-] Searching For Subdomains in Crt.sh
[-] Searching For Subdomains in CertDB
[-] Searching For Subdomains in Certspotter
[-] Searching For Subdomains in Threatcrowd
[-] Searching For Subdomains in Findsubdomains
[-] Searching For Subdomains in DNSDumpster
[-] Searching For Subdomains in PassiveTotal
[-] Searching For Subdomains in PTRArchive
[-] Searching For Subdomains in Hackertarget
[-] Searching For Subdomains in Virustotal
[-] Searching For Subdomains in Securitytrails
[-] Searching For Subdomains in WaybackArchive
[-] Searching For Subdomains in ThreatMiner
[-] Searching For Subdomains in Riddler
[-] Searching For Subdomains in Netcraft
[-] Searching For Subdomains in Dnsdb
[-] Searching For Subdomains in Baidu
[-] Searching For Subdomains in Bing
[-] Searching For Subdomains in Ask

[+] Finding subdomains for : 
error: json: cannot unmarshal object into Go value of type []certspotter.certspotter_object
```

**Comment by Ice3man543** [comment]
Hey @madaratech I recently pushed some code adding domain list and recursion support. It is due to some errors there that I forgot to add message. I will do it in about an hour or so. Thanks for informing.

**Comment by Ice3man543** [comment]
Fixed in commit 25858f557a95ef4a9c33f82d9eec73f7ae0a6cbb. Thanks for notifying !

**Comment by madaratech** [comment]
Nice! 

1 more thing, is that typo? **top** instead of **to**? @Ice3man543 

![image](https://user-images.githubusercontent.com/8293321/39666661-d9162230-50c4-11e8-8ed7-d3b53567c424.png)

**Comment by Ice3man543** [comment]
Yeah
Will be fixing that soon.

**Comment by Ice3man543** [comment]
Done. @madaratech :d
