### ISSUE TITLE
Create better install instructions in readme and add comaprison

### ISSUE THREAD

**Issue by Ice3man543** [Ice3man543/subfinder#32]
@codingo We have been talking about this for a while. Would you like to do this or should I?

**Comment by Ice3man543** [comment]
Also, should we combine subdomain takeover detection into this tool?

**Comment by madaratech** [comment]
Hey guys!

subdomain takeover detection would be nice to add, but also want to suggest few things to keep in mind which I think will be good to have.

1. Flag to check for subdomain takeover after successful subdomain scan.
2. Flag to check for subdomain takeover for given list of the subdomain.

2nd option would be useful when you want to check for takeover in future but don't want scan again for the subdomain.
