### ISSUE TITLE
Refactor code for golang style guide and idioms

### ISSUE THREAD

**Issue by Ice3man543** [Ice3man543/subfinder#35]
## What's the problem (or question)?
The current code doesn't follows golang proverbs or patterns. The whole code needs a refactor and rewrite using golang ideas to reduce problems and bugs.

## Do you have an idea for a solution?
Just rewrite the code.

## How can we reproduce the issue?
Take a look at the code

**Comment by codingo** [comment]
Also relates to #23. Both bodies of work could be done in conjunction.
