### ISSUE TITLE
Brute force working?

### ISSUE THREAD

**Issue by sl4cky** [Ice3man543/subfinder#54]
Hi, 
Great tool! thanks for sharing. 
Does the brute force functionality work? It doesn't display any output and domains that this module successfully finds, and it seems to be finished quite quickly therefore I am asking. btw would a list with resolvers provide a better result when running brute force? 

Thanks.

**Comment by Ice3man543** [comment]
Hi, 
What command line arguments do you use to run SubFinder? 
Thanks for the nice words.

**Comment by sl4cky** [comment]
./subfinder -d <domain> -silent -b -w names.txt -o subfinder-output

seems like it's not performing brute force because it finish quickly. the wordlist contains 101010 prefixes.

**Comment by Ice3man543** [comment]
Try to use verbose flag to perform bruteforce. Is your text file correctly formatted? Use verbose flag and post your output here.

**Comment by sl4cky** [comment]
Ohh, that fixed the problem, thanks and sorry for the bother, 
It's a great tool thanks a lot! :+1:
