### ISSUE TITLE
Doesn't export to JSON in Centos

### ISSUE THREAD

**Issue by Rhynorater** [Ice3man543/subfinder#58]
## What's the problem (or question)?
It appears that when you use the -oJ and the -o flag on Centos, the file doesn't write out. There are no errors, it just doesn't process the -o flag and thus doesn't write any file

However, using only -o does work. 

## Do you have an idea for a solution?
As a patch, I tried to edit the go code as follows:
```
flag.BoolVar(&s.IsJSON, "oJ", false, "Write output in JSON Format") 
```
to
```
flag.BoolVar(&s.IsJSON, "oJ", true, "Write output in JSON Format") 
```

However, this did not result in any file produced when I ran:
```subfinder -d domain.com -o```
## How can we reproduce the issue?
I know set up is a pain for these things, so I can issue you an account on my Centos server if you contact me through twitter and prove your identity. Otherwise, I would recommend a Centos VM. 

## What are the running context details?
* Client OS: CentOS Linux release 7.4.1708 (Core)
* Program version (see banner): Most recent (as of June 1, 2018)
* Relevant console output (if any): The program simply returns the subdomains, just not in a file.
* Exception traceback (if any): None

**Comment by Rhynorater** [comment]
Just to be clear, the following command doesn't produce any file output:
```subfinder -d domain.com -o test -oJ```

**Comment by Ice3man543** [comment]
Hey @Rhynorater, 
Thanks for reporting this. Can you check the directory permission and everything. Try changing the directory SubFinder is in. Also, can you tell your golang version?

**Comment by Ice3man543** [comment]
Do other output formats like text output, aquatone-style output work?
