### ISSUE TITLE
Add Stateful Browser Support (Eg. Selenium) ?

### ISSUE THREAD

**Issue by Mzack9999** [Ice3man543/subfinder#64]
Would improve web content retrieval when page is generated dynamically by javascript

**Comment by Ice3man543** [comment]
I wanted to add selenium but it has way too many dependencies and also increases the bulkiness of the tool. Another reason for not including it is speed. Selenium is imo spider than net/hml and regex. I believe it's speed we are looking for.

**Comment by Mzack9999** [comment]
Some potential passive sources generate content dynamically with javascript or with user interaction (Eg duckduckgo #60 ), without a stateful browser the combo net/html + regex fails

**Comment by Ice3man543** [comment]
@Mzack9999 You're probably right. I am facing this currently while implementing Dogpile interface :)
@codingo What do you say?
