### ISSUE TITLE
Invalid character 'o' looking for beginning of value

### ISSUE THREAD

**Issue by ZeroDot1** [Ice3man543/subfinder#72]
I've seen this 2 times now, is that a bug?
Screenshot: 
![bildschirmfoto vom 2018-06-10 22-51-19](https://user-images.githubusercontent.com/28985171/41206215-2a1efd34-6d01-11e8-8a28-64650989f5ca.png)

**Comment by Ice3man543** [comment]
Nope. It's not. It's just a failed attempt at error handling :(
