### ISSUE TITLE
Implement SecurityTrails

### ISSUE THREAD

**Issue by ZeroDot1** [Ice3man543/subfinder#74]
This is a very effective tool, I got many subdomains in my test very quickly. 
https://securitytrails.com/
https://securitytrails.com/corp/features

API DOCs:
https://securitytrails.com/corp/apidocs

Test: 
https://securitytrails.com/list/apex_domain/google.com
https://securitytrails.com/list/apex_domain/coinhive.com

**Comment by codingo** [comment]
I imagine you already figured this out (given the closure) but this is already implemented at: https://github.com/Ice3man543/subfinder/tree/master/libsubfinder/sources/securitytrails

**Comment by ZeroDot1** [comment]
@codingo I overlooked it, I'm practically completely blind, that can happen sometimes, sorry.
