### ISSUE TITLE
Move to an organization repo?

### ISSUE THREAD

**Issue by Ice3man543** [Ice3man543/subfinder#81]
@codingo @Mzack9999 As discussed earlier, it's probably time to move to a dedicated subfinder repo!
I'd be happy to port it over to some organization repo. Would make collaboration more easier and decentralized?
Thoughts?

**Comment by codingo** [comment]
I think that's largely your decision, but I'm ok with it. It would make it easier for others to find the project over time (cleaner urls to recall). Going to close this issue to reduce public visibility and to limit the discussion to @Mzack9999 and I (we can comment on the closed issue).

**Comment by Ice3man543** [comment]
@codingo Mzack9999 has already agreed to this! We are moving.
